version: '3'
services:
  frontend:
    build: frontend/ # Especificamos o contexto, ou seja, a pasta onde est√° o Dockerfile.
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./logs:/var/log/frontend # nome do disco virtual : caminho no container
    networks:
      - rede-virtual-1
  backend:
    build: backend/ # Mesmo caso aqui.
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1 # Especificamos a Imagem Docker diretamente.
    restart: on-failure
    volumes:
      - dados-do-banco:/data/db # nome do disco virtual : caminho no container
    networks:
      - rede-virtual-2

volumes:
  dados-do-banco:


networks:
  rede-virtual-1:
  rede-virtual-2:
